/**
 * Test-only helpers for reading the checked-in golden files generated by
 * scripts/gen-golden.py and the vendored UI-Mate resources.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
export const PACKAGE_ROOT = resolve(HERE, "..", "..");
export const GOLDEN_DIR = resolve(PACKAGE_ROOT, "test", "golden");
export const VENDORED_DIR = resolve(PACKAGE_ROOT, "..", "..", "third_party", "ui-mate");

export function readGoldenText(name: string): string {
  return readFileSync(resolve(GOLDEN_DIR, name), "utf8");
}

export function readGoldenJson<T>(name: string): T {
  return JSON.parse(readGoldenText(name)) as T;
}

export interface TrajectoryStep {
  readonly image: string;
  readonly recorded_action: string;
  readonly recorded_response: string;
}

export interface Trajectory {
  readonly instruction: string;
  readonly steps: readonly TrajectoryStep[];
}

export function readTrajectory(): Trajectory {
  return JSON.parse(readFileSync(resolve(VENDORED_DIR, "resources", "trajectory.json"), "utf8")) as Trajectory;
}
